CREATE TABLE DIETPLAN.VITAMINE 
   (	ID NUMBER(*,0) NOT NULL ENABLE, 
	CREATED_AT TIMESTAMP (6) NOT NULL ENABLE, 
	LAST_MODIFIED TIMESTAMP (6) NOT NULL ENABLE, 
	VITAMIN_A_RETINOL BINARY_FLOAT, 
	VITAMIN_A_BETACAROTIN BINARY_FLOAT, 
	VITAMIN_B1 BINARY_FLOAT, 
	VITAMIN_B2 BINARY_FLOAT, 
	VITAMIN_B6 BINARY_FLOAT, 
	VITAMIN_B12 BINARY_FLOAT, 
	VITAMIN_C BINARY_FLOAT, 
	VITAMIN_D BINARY_FLOAT, 
	VITAMIN_E BINARY_FLOAT, 
	VITAMIN_K BINARY_FLOAT, 
	FOOD_ID NUMBER(*,0) NOT NULL ENABLE
   ) ;
ALTER TABLE DIETPLAN.VITAMINE ADD CONSTRAINT PK_VITAMINE PRIMARY KEY (ID) ENABLE;
ALTER TABLE DIETPLAN.VITAMINE ADD CONSTRAINT FK_VITAMINE_FOOD FOREIGN KEY (FOOD_ID)
	  REFERENCES DIETPLAN.FOOD_METADATA (ID) ENABLE;
CREATE UNIQUE INDEX DIETPLAN.PK_VITAMINE ON DIETPLAN.VITAMINE (ID) 
  ;
