    INSERT INTO tagesbedarf_mineralstoffe (
        id,
        created_at,
        last_modified,
        calcium,
        chlorid,
        eisen,
        fluorid,
        iodid,
        kalium,
        kupfer,
        mangan,
        magnesium,
        natrium,
        phosphor,
        schwefel,
        zink
    ) VALUES (
        1,
        systimestamp,
        systimestamp,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2
    );
/

    INSERT INTO tagesbedarf_vitamine (
        id,
        created_at,
        last_modified,
        vitaminaretinol,
        vitaminabetacarotin,
        vitaminb1,
        vitaminb2,
        vitaminb6,
        vitaminb12,
        vitaminc,
        vitamind,
        vitamine,
        vitamink
    ) VALUES (
        1,
        systimestamp,
        systimestamp,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2
    );
/