CREATE TABLE "DIETPLAN"."TAGESBEDARF_VITAMINE" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"LAST_MODIFIED" TIMESTAMP (6) NOT NULL ENABLE, 
	"VITAMINARETINOL" BINARY_FLOAT, 
	"VITAMINABETACAROTIN" BINARY_FLOAT, 
	"VITAMINB1" BINARY_FLOAT, 
	"VITAMINB2" BINARY_FLOAT, 
	"VITAMINB6" BINARY_FLOAT, 
	"VITAMINB12" BINARY_FLOAT, 
	"VITAMINC" BINARY_FLOAT, 
	"VITAMIND" BINARY_FLOAT, 
	"VITAMINE" BINARY_FLOAT, 
	"VITAMINK" BINARY_FLOAT
   ) ;
  ALTER TABLE "DIETPLAN"."TAGESBEDARF_VITAMINE" ADD CONSTRAINT "PK_TAGESBEDARF_VITAMINE" PRIMARY KEY ("ID") ENABLE;
  CREATE UNIQUE INDEX "DIETPLAN"."PK_TAGESBEDARF_VITAMINE" ON "DIETPLAN"."TAGESBEDARF_VITAMINE" ("ID") 
  ;
