CREATE TABLE "DIETPLAN"."BRENNSTOFFE" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"FETT" BINARY_FLOAT, 
	"EIWEISS" BINARY_FLOAT, 
	"KOHLENHYDRATE" BINARY_FLOAT, 
	"FOOD_ID" NUMBER(10,0) NOT NULL ENABLE
   ) ;
  ALTER TABLE "DIETPLAN"."BRENNSTOFFE" ADD CONSTRAINT "PK_BRENNSTOFFE" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "DIETPLAN"."BRENNSTOFFE" ADD CONSTRAINT "FK_BRENNSTOFFE_FOOD" FOREIGN KEY ("FOOD_ID")
	  REFERENCES "DIETPLAN"."FOOD" ("ID") ENABLE;
  CREATE UNIQUE INDEX "DIETPLAN"."PK_BRENNSTOFFE" ON "DIETPLAN"."BRENNSTOFFE" ("ID") 
  ;
