CREATE TABLE "DIETPLAN"."FOOD" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100)
   ) ;
  ALTER TABLE "DIETPLAN"."FOOD" ADD CONSTRAINT "PK_FOOD" PRIMARY KEY ("ID") ENABLE;
  CREATE UNIQUE INDEX "DIETPLAN"."PK_FOOD" ON "DIETPLAN"."FOOD" ("ID") 
  ;
