CREATE TABLE "DIETPLAN"."MINERALSTOFFE" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CALCIUM" BINARY_FLOAT, 
	"CHLORID" BINARY_FLOAT, 
	"EISEN" BINARY_FLOAT, 
	"FLUORID" BINARY_FLOAT, 
	"IODID" BINARY_FLOAT, 
	"KALIUM" BINARY_FLOAT, 
	"KUPFER" BINARY_FLOAT, 
	"MANGAN" BINARY_FLOAT, 
	"MAGNESIUM" BINARY_FLOAT, 
	"NATRIUM" BINARY_FLOAT, 
	"PHOSPHOR" BINARY_FLOAT, 
	"SCHWEFEL" BINARY_FLOAT, 
	"ZINK" BINARY_FLOAT, 
	"FOOD_ID" NUMBER(10,0) NOT NULL ENABLE
   ) ;
  ALTER TABLE "DIETPLAN"."MINERALSTOFFE" ADD CONSTRAINT "PK_MINERALSTOFFE" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "DIETPLAN"."MINERALSTOFFE" ADD CONSTRAINT "FK_MINERALSTOFFE_FOOD" FOREIGN KEY ("FOOD_ID")
	  REFERENCES "DIETPLAN"."FOOD" ("ID") ENABLE;
  CREATE UNIQUE INDEX "DIETPLAN"."PK_MINERALSTOFFE" ON "DIETPLAN"."MINERALSTOFFE" ("ID") 
  ;
